
export const listCity = [
    "Ambon",
    "Balikpapan",
    "Banda Aceh",
    "Bandar Lampung",
    "Bandung",
    "Banjar",
    "Banjarbaru",
    "Banjarmasin",
    "Batam",
    "Batu",
    "Baubau",
    "Bengkulu",
    "Bima",
    "Binjai",
    "Bitung",
    "Blitar",
    "Bogor",
    "Bontang",
    "Bukittinggi",
    "Cilegon",
    "Cimahi",
    "Cirebon",
    "Denpasar",
    "Depok",
    "Dumai",
    "Gorontalo",
    "Gunungsitoli",
    "Jakarta",
    "Jambi",
    "Jayapura",
    "Jepara",
    "Jombang",
    "Jacksonville",
    "Johannesburg",
    "Kediri",
    "Kendari",
    "kotamobagu",
    "Kupang",
    "Langsa",
    "Lhokseumawe",
    "Lubuk Linggau",
    "Madiun",
    "Magelang",
    "Makassar",
    "Malang",
    "Manado",
    "Mataram",
    "Medan",
    "Metro",
    "Mojokerto",
    "Padang",
    "Padang Panjang",
    "Padangsidimpuan",
    "Pagar Alam",
    "Palangka Raya",
    "Palembang",
    "Palopo",
    "Palu",
    "Pangkalpinang",
    "Parepare",
    "Pariaman",
    "Pasuruan",
    "Payakumbuh",
    "Pekalongan",
    "Pekanbaru",
    "Pematangsiantar",
    "Pontianak",
    "Prabumulih",
    "Probolinggo",
    "Sabang",
    "Salatiga",
    "Samarinda",
    "Sawahlunto",
    "Semarang",
    "Serang",
    "Sibolga",
    "Singkawang",
    "Solok",
    "Sorong",
    "Subulussalam",
    "Sukabumi",
    "Sungai Penuh",
    "Surabaya",
    "Surakarta",
    "Tangerang",
    "Tangerang Selatan",
    "Tanjungbalai",
    "Tanjungpinang",
    "Tarakan",
    "Tasikmalaya",
    "Tebing Tinggi",
    "Tegal",
    "Ternate",
    "Tidore Kepulauan",
    "Tomohon",
    "Tual",
    "Yogyakarta"
]